name: Push CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v2
        with:
          command: ${{ matrix.command }}
          node-version: 20

    strategy:
      fail-fast: false
      matrix:
        command: ["eslint", "prettier", "test:ci", "compile"]

on: push
